### ISSUE TITLE
Reputation Score (EPIC)

### ISSUE THREAD

**Issue by 0xjona** [protocol/retrieval-pinning#58]
We are developing the reputation score mechanism, integrating it into the product.

Here’s a checklist:
- [ ] #2 @irene will provide the formula
- [ ] #60 @Steve-Rog and @turinglabsorg will implement the software
- [ ] #61 @claudiofabbro will design the leaderboard page, and @Steve-Rog will implement it

We’ll have a discussion about #59 with @lucaniz and @nicola and move consequently

**Comment by irenegia** [comment]
should we add this to epic 4 (open the issue)?
