### ISSUE TITLE
onchain storage - design & implementation

### ISSUE THREAD

**Issue by 0xjona** [protocol/retrieval-pinning#83]
Here we track both design and implementation of
- [ ] retrieval pinning protocol updated website
- [ ] new onchain.storage homepage
- [ ] dapp updated (storage deals UX featuring retrieval pinning protocol atm)  

_about PROCESS_
**desing steps**
We expect to 
- brainstorm and have design docs with requested features
- have all the designs via FIGMA
- collect feedbacks on functionalities and experience via FIGMA comments
- eventually report _in this github issue_ questions that needs further brainstorming

**implementation steps**
- from FIGMA designs to updated websites and dapp
- check-ins with designers and developers about specs
- we can collect feedbacks via [slack channel ](https://filecoinproject.slack.com/archives/C03CJKWP2DR)or _in this github issue_
- iterate

Feedbacks can be 
- **fix requests & bug reports** to be immediately resolves
- elements that need to be redesigned (we start again from **design steps**)
- elements that have not been correctly translated from design to code

**Comment by 0xjona** [comment]
**dApp improvements**:
  - [ ] If someone wants to allow us to check them they add us as an appeal key (suggest this via UX)
  - [ ] add multiple appeal addresses (+ other improvements already pointed out in the figma)
  - [ ] loading status and notification system (related to appeals)
  - [ ] onchain database vs api https://github.com/turinglabsorg/ipdb

**Comment by Steve-Rog** [comment]
Based on the call we had with @0xjona  this morning I will focus on fixing the following bugs/improvements for the next steps:

**DASHBOARD**
- Fixing the "redundancy" for downloading/displaying the file (deal).
- Replacing the "refresh" button with "delete deal" (with confirmation prompt)
- #72 

**DEAL CREATION**
- Ability to add more appeal address and tooltip to explain this new feature to the user.

**OTHERS**:
- Optimize "blocking" loading screens for the user. #73 
- Implement the withdraw function for the user. #78

We will also coordinate with @claudiofabbro  where needed.

**Comment by irenegia** [comment]
@0xjona will move this issue in the on-chain-storage repo

**Comment by Steve-Rog** [comment]
Improvements and bug fixing:

**DASHBOARD**
- Replacing the "refresh" button with "delete deal" (with confirmation prompt): 60%
- Optimize "blocking" loading screens for the user. 50%
- Fixed bug of refreshing deal information in live (no need to refresh the whole page)
- Optimized the function of the search bar
